tasks:
  - name: create-dbs
    actions:
      - description: Create the DB test package for the PG instance
        cmd: uds zarf package create src/test --confirm --no-progress --architecture=${UDS_ARCH} --skip-sbom
      - description: Deploy the test package into the cluster
        cmd: "uds zarf package deploy ../build/zarf-package-postgres-test-* --confirm"

  - name: health-check
    actions:
      - description: Postgresql Cluster Status
        wait:
          cluster:
            kind: Postgresql
            name: pg-cluster
            namespace: acid
            condition: "'{.status.PostgresClusterStatus}'=Running"
